### ISSUE TITLE
库打包时的 tree-shaking 的疑问

### ISSUE THREAD

**Issue by 9-lives** [demos-platform/tree-shaking#1]
请问有测试过库打包，被其它项目引用的场景的 tree-shaking 吗？我用  webpack5 简单尝试，没有成功。

1. 库 package.json 声明 module: "./dist/index.js" 和 sideEffects: false ;
1. webpack.config.js 配置 output.library.type: 'module' 和 experiments.outputModule: true 将库文件打包成 es module 语法的文件 dist/index.js，此时 index.js 具有全量代码，正常；
2. 库 npm link；
3. 业务项目 link 该库, import index.js 的某个方法;
4.  业务项目 build，构建产物包含没有用到的库代码，未达到预期效果；

**Comment by MuYunyun** [comment]
> 请问有测试过库打包，被其它项目引用的场景的 tree-shaking 吗？我用 webpack5 简单尝试，没有成功。
> 
> 1. 库 package.json 声明 module: "./dist/index.js" 和 sideEffects: false ;
> 2. webpack.config.js 配置 output.library.type: 'module' 和 experiments.outputModule: true 将库文件打包成 es module 语法的文件 dist/index.js，此时 index.js 具有全量代码，正常；
> 3. 库 npm link；
> 4. 业务项目 link 该库, import index.js 的某个方法;
> 5. 业务项目 build，构建产物包含没有用到的库代码，未达到预期效果；

你可以在第二步打包的时候对打包产物进行拆分，这样子就可以达到按需引用的效果了。举个 case ，你可以参考下社区组件库 按需引用的实践。
